### PR TITLE
Align CCA naming in README to CCA specs

### LINKED ISSUE #15: CCA support
Add a `cca` sub-command to:

* [x] create a CCA token from a claims-set, platform and realm secret keys
* [x] check the integrity of a CCA token given a matching platform public key
* [x] run a challenge-response session with a Veraison verifier both as RP and Attester
* [x] also add the necessary documentation
* [x] align naming of keys with public CCA documentation

### PR DESCRIPTION
**Pull request by yogeshbdeshpande**
Fix #15

### CODE REVIEW

**Review by thomas-fossati — COMMENTED** [review]
This is not sufficient: the help strings as well as the parameters declarations of the check, create and verify command files need to be updated as well.

**Comment by yogeshbdeshpande** [comment]
> This is not sufficient: the help strings as well as the parameters declarations of the check, create and verify command files need to be updated as well.

Good catch!

**Comment by yogeshbdeshpande** [comment]
@thomas-fossati I think, I have checked now it is complete!

**Review by thomas-fossati — APPROVED** [review]
thanks!

Thoughts:
1. We need to tag a new release (see next point);
1. This is potentially a breaking change.  If we decide not to be backwards compatible (i.e., making `--pak` an alias of `--iak`) we need to bump the major number (i.e., v2.0.0)
1. If we don't do the aliasing thing, we need to update the callers (e.g., I think the services' integration tests needs fixing)

**Comment by yogeshbdeshpande** [comment]
> * need to bump the major number (i.e., v2.0.0)

I agree with your observation:

I will tag a new release with tag v2.0.0

I would prefer the route of fixing entire `Veraison` code base to have a consistent naming as per the specification, so will raise a github issue on services to upgrade `evcli` command usage to comply with v2.0.0

Thanks for your review!

**Comment by yogeshbdeshpande** [comment]
> > * need to bump the major number (i.e., v2.0.0)
> 
> I agree with your observation:
> 
> I will tag a new release with tag v2.0.0
> 
> I would prefer the route of fixing entire `Veraison` code base to have a consistent naming as per the specification, so will raise a github issue on services to upgrade `evcli` command usage to comply with v2.0.0
> 
> Thanks for your review!

After checking the `services` `integration-tests` does not need an edit but `end-to-end` does need it.

As the docker deployment always pulls `evcli@latest`

**Pull request merged**
